# Generated by Django 5.0.6 on 2024-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
    ]
