"""
Django settings for sqldb_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x$5@6j65k=0g&ba0w787^d+f0eoc&m02f5uxg5le#v9y(a@q^u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sqldb_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [BASE_DIR, 'home', 'templates'], 
            #  [BASE_DIR/,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sqldb_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    
    
}

# MANUALLY GENERATED TO STORE THE USER DATA'
# sqldb_project/settings.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'user_data',  # This is where home_inquiry table should be
        'USER': 'root',
        'PASSWORD': 'Rajshree@1108',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'employees_mod': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'employees_mod',
        'USER': 'root',
        'PASSWORD': 'Arpita@2806',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# DATABASES = {
#     'default':{
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'user_data',# Database name 
#         'USER': 'root',
#         'PASSWORD': 'Rajshree@1108', # your_database_password
#         'HOST': 'localhost',  # Or your database server
#         'PORT': '3306',       # Default MySQL port
#     },
#     'output_data': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'employees_mod',
#         'USER': 'root',
#         'PASSWORD': 'Arpita@2806',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }
    
    
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
import os 
# ## STATIC File added MANUALLY
STATICFILES_DIRS = [
    os.path.join(BASE_DIR / "static") ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OPENAI API KEY
import os

os.environ["OPENAI_API_KEY"] = "sk-proj-fPzFShpxCG5z46rojI2uT3BlbkFJ4Z7OU1dSkrAijWWSYQ9x"  # Replace with your actual API key